#include <stdio.h>
#include <inttypes.h>

#define __STDC_FORMAT_MACROS
/*
The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
*/

int main(){

  uint64_t sum = 0;
  int acc = 0;
  int comut = 1;
  uint64_t i = 0;
  uint64_t j = 0;

  while(comut){
    sum+=i;
    for(j = 1; j<=sum; j++){
      if(sum/j*j == sum){
        acc++;
      }
    }
    if(acc > 500){comut = 0; printf("%" PRIu64 "\n", sum);}
    acc = 0;
    i++;
    }

  return 0;

}
